#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#
# helm install syncthing k8s-home-lab/syncthing -f mediacenter/helm/3_others/syncthing/values.yml

image:
  # -- image repository
  repository: syncthing/syncthing
  # -- image tag
  tag:
  # -- image pull policy
  pullPolicy: IfNotPresent

env:
  TZ: Europe/Zurich
  PUID: 1030
  PGID: 100

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    enabled: true
    type: LoadBalancer

    ports:
      http:
        port: 8384
        enabled: true

  listen:
    enabled: true
    type: NodePort
    externalTrafficPolicy: Local
    ports:
      listen:
        enabled: true
        port: 22000
        protocol: TCP
        targetPort: 22000

  discovery:
    enabled: true
    type: NodePort
    externalTrafficPolicy: Local
    ports:
      discovery:
        enabled: true
        port: 21027
        protocol: UDP
        targetPort: 21027

ingress:
  main:
    enabled: true
    primary: true
    nameOverride:
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    labels: {}
    ingressClassName:  traefik # "nginx"
    hosts:
      - host: syncthing.gygax.cloud
        paths:
          - path: /
            pathType: Prefix
            service:
              name: syncthing
              port: 8384

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: true
    type: pvc
    mountPath:  /data # /config
    readOnly: false
    nameOverride: data
    storageClass:  # "-"
    existingClaim: media-pvc # your-claim
    subPath: # some-subpath
    accessMode: ReadWriteMany
    size: 5Ti
    retain: true
  config:

    enabled: true
    type: pvc
    mountPath: /var/syncthing/config
    readOnly: false
    nameOverride: config
    storageClass:  longhorn # "-"
    existingClaim: # your-claim
    subPath: # some-subpath
    accessMode: ReadWriteOnce
    size: 3Gi
    retain: true